### ISSUE TITLE
Add nav spec to Neighborhood Report frontmatter

### ISSUE THREAD

**Issue by mmontesanonyc** [nycehs/ehs-data-portal-frontend-temp#10]
This can wait, but eventually, each Neighborhood Report markdown file will need an additional item in the frontmatter:

```
menu:
    main:
        identifier: '04'
```

This will ensure that the nav menu is highlighted for subpages in a content area, not just for the landing page in a content area. Other content areas can be done by hand, but there are a lot of NR .md files.

**Comment by mmontesanonyc** [comment]
@cgettings, after that rundown from Grant on python scripts that generate Neighborhood Reports material - there are a couple issues that I'd love for you to dig into.

This is a simple one (I think) adding code to [NR_content_md_writer.py](https://github.com/nycehs/NeighborhoodReports/blob/master/Python%20Data%20Management/NR_content_md_writer.py) to add the following in the frontmatter:
```
menu:
    main:
        identifier: '04'
```

**Comment by mmontesanonyc** [comment]
There's a branch for this [here](https://github.com/nycehs/ehs-data-portal-frontend-temp/tree/hotfix-NR-nav-frontmatter).

**Comment by cgettings** [comment]
Addressed this in a [commit on Portal-Prototype-Working-Files](https://github.com/nycehs/Portal-Prototype-Working-Files/commit/25e98b994216a616e6fcd39ced6386fc5e50baee). Not sure of the best way to get these changes into hotfix-NR-nav-frontmatter.

**Comment by mmontesanonyc** [comment]
That looks right! 

OK, so if you open hotfix-NR-nav-frontmatter on your local, and then move all of the .md files into that branch of this repo (in the right folder - `content/neighborhood_reports/etc` - then, you'll be able to test it out locally: in the terminal, run `hugo serve --environment local --disableFastRender`, navigate to the neighborhood reports, and when you're on the individual report pages, the Neighborhood Reports button in the nav bar should have an active state. 

If that works, commit, push, and we'll merge it in.

**Comment by mmontesanonyc** [comment]
Took the opportunity to merge and rebuild!
