### ISSUE TITLE
Non-trend data files should have only 1 year

### ISSUE THREAD

**Issue by cgettings** [nycehs/ehs-data-portal-frontend-temp#131]
For now, for that file, yup - there are two filetypes, [Indicator].csv and [Indicator}_trend.csv - so for the former, most recent year only. There may be some efficiencies we can work in down the line.

_Originally posted by @mmontesanonyc in https://github.com/nycehs/ehs-data-portal-frontend-temp/issues/130#issuecomment-998170700_

**Comment by cgettings** [comment]
@mmontesanonyc Looks good after my last commit:

![Screenshot (327)](https://user-images.githubusercontent.com/12686912/146829109-0365c631-e5f4-41cf-b24c-a6a162e00cc0.png)

**Comment by mmontesanonyc** [comment]
Looking great - thank you!
I went ahead and added a couple commits on this branch that are working toward finalization (sliiightly out of focus for our branching scheme but I think we can consider this a branch for a bit of finalization work) - revising the tooltip and labels a little bit, too.
