### ISSUE TITLE
NRs: AQ trend data shows annual and seasonal data

### ISSUE THREAD

**Issue by mmontesanonyc** [nycehs/ehs-data-portal-frontend-temp#132]
Here's one that I only just noticed - with the data files in place, we've got different timetypes in the AQ trend charts. I think the most straightforward way to solve this is at the data level, revising the AQ indicator trend files to only include annual averages. 

![image](https://user-images.githubusercontent.com/55593359/148436216-921dfe42-63e7-4940-902b-fd77cdd23bf6.png)

**Comment by mmontesanonyc** [comment]
This is safe to close too, right? The change is live in NR-data-update, soon to be merged into development and main.

**Comment by cgettings** [comment]
There's still some edge cases, like this:

![Ozone](https://user-images.githubusercontent.com/12686912/150362731-b03f3a06-1dd9-43c8-a02e-bf6b64e8e6f9.png)

**Comment by cgettings** [comment]
Ozone is the only indicator that has seasonal data but no annual average, so fix keeping the seasonal value is hard-coded.
