### ISSUE TITLE
Indicator names include "children" when the data is about adults

### ISSUE THREAD

**Issue by cgettings** [nycehs/ehs-data-portal-frontend-temp#134]
![Screenshot (3)](https://user-images.githubusercontent.com/12686912/150006377-d6646ef3-aaeb-4d1a-be38-78b5fe9c0015.png)

There are a couple other examples in the Air Quality report, also.

**Comment by cgettings** [comment]
This is a data structure problem. The titles come from `short_name` in `internal_indicator`, which is at the Indicator level, and the Measures define different age groups. In other cases, like regular Asthma ED visits, the different age groups are defined by different Indicators, so the `short_name` titles work.

I think the solution is to identify the Indicators where this is a problem, and then change those titles after pulling them from the database. We can punt on the data structure conversation.

**Comment by cgettings** [comment]
No, you have it right. I'm not sure why it's different measures in this case. We could always add new indicators and redefine the old ones to be just one age group. In fact I think it makes sense to formally define "indicators" and "measures" in a way that doesn't allow this situation. Then, at some point, we can go through and change them all to be consistent with the definition.

**Comment by mmontesanonyc** [comment]
Yes, it would be much better for age group (and geography - and perhaps others?) to be a distinction at the measure level - currently, on Asthma for example, the indicator list forces a user to make the choice of indicator, geography, AND age group. That's too much - let's flag this as a data-organization project to tackle this year, though it might have to wait until after we launch the new portal. 

For now - let's chat through solutions to this NR problem in our meeting today. 

![image](https://user-images.githubusercontent.com/55593359/150360791-fda6d849-cbd9-4062-ba9a-5eafaa0ed814.png)

**Comment by cgettings** [comment]
Yeah, adding age group to a select list does make sense. (Of course, that would mean doing the opposite of what I suggested above.)

**Comment by cgettings** [comment]
Issue fixed in my last commit. Structural issue placed in a cupboard on a high shelf.
