### ISSUE TITLE
NR: finalizations before launch

### ISSUE THREAD

**Issue by mmontesanonyc** [nycehs/ehs-data-portal-frontend-temp#138]
- [x] Merge recent changes from NR-data-update into development and main
- [x] Create new branch for deployable NRs (this won't merge into other branches)
- [x] Remove other content (convert to draft)
- [x] Add extant analytics code
- [x] Update BaseURL
- [x] Update Home link to live site URL
- [x] Add modal with input and email address form
- [x] Run build for this branch

Other work:
- [x] Deploy build to development server
- [x] Test and revise
- [x] Deploy to production
- [x] Test and revise
- [x] Update Portal Home Page link to NRs
- [x] put up alert box on old NRs

**Comment by mmontesanonyc** [comment]
I noticed one other issue while QCing - the units for Childhood Lead Levels (in the Housing report) are borked:

![image](https://user-images.githubusercontent.com/55593359/150824245-49e5b0b8-5d32-49c1-bb80-b0567bdc374e.png)

This seems to come out of the report json in data/reports. That is, it's a content issue not a FE/display issue:
![image](https://user-images.githubusercontent.com/55593359/150824400-a2bbb714-c7d7-4f7e-97cb-718ebea84f9a.png)

@cgettings, can you tackle that? We could do a find and replace on data/reports json to replace that with a mu, but the output script that generates those files would need to be updated, too, otherwise we'll find ourselves in the same situation down the line.

**Comment by mmontesanonyc** [comment]
Instead of removing other content I just updated the nav so that it only includes Home (pointing to actual portal server link, not prototype home) and NRs.

**Comment by mmontesanonyc** [comment]
New branch, deploy-Neighborhood-Reports, built with a deployment config file. `hugo serve --environment deploy` to test.

**Comment by mmontesanonyc** [comment]
I've added an analytics code and a modal that pops up on landing on the NRs and links to a very brief survey.

Run a build to the /docs folder so this is basically ready to drop onto our server and test to make sure that it's all functioning as expected.

**Comment by cgettings** [comment]
Some things about the NR on dev:

1. Search doesn't work, directs to http://devnetbesp201/ehs-data-portal-frontend-temp/search_results/index.html?search={search_term}
2. Add option to go to current NR version (QuickView)?
3. Data download from a neighborhood report directs here: https://a816-dohbesp.nyc.gov/IndicatorPublic/EPHTCsv/Asthma_and_the_Environment.csv, which doesn't work
4. Link to "Asthma and Environment Neighborhood Report" on portal Asthma page goes to the old version (https://a816-dohbesp.nyc.gov/IndicatorPublic/QuickView.aspx). Not necessarily a problem now, but when fully deployed, we'll have to change all these links.

**Comment by mmontesanonyc** [comment]
I wound up pulling the data download button, as the most direct route to launching as asap as possible. but let's think about the best way to handle that for the full-portal launch.
