### ISSUE TITLE
units for Childhood Lead Levels (in the Housing report) are borked

### ISSUE THREAD

**Issue by cgettings** [nycehs/ehs-data-portal-frontend-temp#141]
I noticed one other issue while QCing - the units for Childhood Lead Levels (in the Housing report) are borked:

![image](https://user-images.githubusercontent.com/55593359/150824245-49e5b0b8-5d32-49c1-bb80-b0567bdc374e.png)

This seems to come out of the report json in data/reports. That is, it's a content issue not a FE/display issue:
![image](https://user-images.githubusercontent.com/55593359/150824400-a2bbb714-c7d7-4f7e-97cb-718ebea84f9a.png)

@cgettings, can you tackle that? We could do a find and replace on data/reports json to replace that with a mu, but the output script that generates those files would need to be updated, too, otherwise we'll find ourselves in the same situation down the line.

_Originally posted by @mmontesanonyc in https://github.com/nycehs/ehs-data-portal-frontend-temp/issues/138#issuecomment-1020293495_

**Comment by mmontesanonyc** [comment]
All set, thanks for that fix! merged into development, main, and deploy-NRs.
