### ISSUE TITLE
Prep for viz module contract kick-off

### ISSUE THREAD

**Issue by mmontesanonyc** [nycehs/ehs-data-portal-frontend-temp#151]
General:
- [x] Review/refine business rules
- [ ] Additional work on table spec?
- [x] Finish Indicators.json with VisOptions
- [x] Re-naming flurry re: SEO optimization 
- [x] Have subtopic front matter ready-to-go (with Indicator array with Indicator IDs)
- [x] Clean branches, get them UTD, and create visualization working branch

**Comment by mmontesanonyc** [comment]
Some details/documentation on updating the frontmatter...

Subtopic frontmatter currently looks like this:
![image](https://user-images.githubusercontent.com/55593359/152800742-bdb8a9b5-02d5-4c15-b5ba-59172212443c.png)

What we'll need is an additional field - perhaps let's call it `indicator` so that we're still using that word but we can distinguish from `indicators` (or we could change the current `indicators` to `indicatorsOld` and use `indicators` for this new field - that would require only a small update to the current data explorer template that uses `.Params.indicators` for the list of links to the indicators).

The new indicators field would need just a list of the indicator IDs (i forget - `internal_id`?). So:

`indicators: [2390, 2181, 2158, 2157, ...]`

Two questions about this, for us to consider:
One thing we chatted about last week is how to incorporate instances where we have indicators sorted by header:
![image](https://user-images.githubusercontent.com/55593359/152802011-aad25cd6-736a-400d-8079-c62025017403.png)

And, I'm not sure of the answer. It may be to do something like the below - 
`Indicators: [
       {"header": "Header Name",
       "indicators:" [xxxx, yyyy, zzzz]},
       {"header": "Header Two Name",
       "indicators:" [aaaa, bbbb, cccc]}
]

I'm not sure offhand how the page template would handle both approaches - I suppose it would look for Indicators[0].header and if it exists, display the headers and the nested indicators; and if it doesn't exist, then it would just loop through `Indicators` and display the Indicators.

The other question is, just associating the subtopic with indicators by indicator IDs means that the page template will read the indicators in the frontmatter, and then look those up in Indicators.json, retrieve their names, and display those on the page. Will that affect performance? Is there a better way to do that? Might be a question for our contractor, before we go too far down the line on this.

**Comment by mmontesanonyc** [comment]
@cgettings

**Comment by cgettings** [comment]
Actually, `isset` would probably work for this.

**Comment by mmontesanonyc** [comment]
Oh, right. In my initial write-up I was thinking about how it could be done with JS, not with Hugo. 

Let's start this way - can you commit a revision to the subtopic markdown in this branch that has the `indicators` formatted how we'll need them (those with headers, those without) and then we can figure out later on if we can use `isset` or if we need to add `header:` to the frontmatter?

**Comment by cgettings** [comment]
@mmontesanonyc Have a working example for Asthma in [my last commit](https://github.com/nycehs/ehs-data-portal-frontend-temp/commit/ea7aa217d92d1167e88842da117679e2ab6803b7).

**Comment by mmontesanonyc** [comment]
That looks like a tidy solution. From there, the page would also be able to grab indicators.json, match the indicator names to the IDs, and display the indicator names in the dropdown list. I think that works but we'll want to review/confirm with Chris @ BB.

**Comment by cgettings** [comment]
It seems to work with Asthma, but I didn't do much testing. I think it's a good place to start, and I can't wait to see what a real pro can do with it 👌

**Comment by mmontesanonyc** [comment]
Hey @cdoss-bbox, knowing we've got a meeting this week, wanted to call your attention to our chatter about indicator frontmatter in the subtopic markdown files. This follows up on our email after the previous meeting; we can chat more later this week.

**Comment by mmontesanonyc** [comment]
@cgettings I think we can close this one out, yeah?
