### ISSUE TITLE
Develop data index page

### ISSUE THREAD

**Issue by mmontesanonyc** [nycehs/ehs-data-portal-frontend-temp#163]
In conversation with Mike, an idea came up for a data index page - a list of indicators, most recent year, and available geographies. 

We can create a page that grabs this from Indicators.json and puts it into a table with some sorts/filters on it. Would be great to sort by recency, filter by geography, and whatnot.

I'm not sure where on the site this page would _live_ but I could see linking to it from search results ("Show all data"?) and some other sections. Almost a sitemap for the data explorer...

**Comment by mmontesanonyc** [comment]
- [ ] Develop index page (@mmontesanonyc )
- [ ] Use Pipes (?) to build file of indicator/subtopic association (@cgettings )

**Comment by mmontesanonyc** [comment]
Data index page built [here](https://github.com/nycehs/ehs-data-portal-frontend-temp/tree/feature-data-index-page). I also added links to it from the search page and from the data explorer main page (the section.html template). Plenty more that can be done:

- Enhance styles and design - like, badges for the different geographies (Maybe exclude Citywide and Borough; use Badges like filters?)
- Use end_period for the time so that we can sort properly by time 
- Link to the datasets (would require Hugo building a file of indicator/subtopic associations)

**Comment by cgettings** [comment]
![Screenshot (358)](https://user-images.githubusercontent.com/12686912/159136521-ed6cb88b-11bd-4c77-a3d4-356883f283f6.png)

**Comment by mmontesanonyc** [comment]
I pushed an enhancement with some work I'd been doing on PPWF - geo badges and a few small tweaks. I also gave the note text you put on the page a `sr-only` class, so the page would stay tidy but we can still see those HTML notes.

I think a few other enhancements could be:
- Printing the measurement types as `<li>`s instead of just printing the array
- Adding a Subtopics column that reads `subtopic_indicators`
- Converting the geo badges into filters

**Comment by cgettings** [comment]
@mmontesanonyc The code's a bit ugly, but everything's in there 🙌

**Comment by mmontesanonyc** [comment]
Very nice. 

Notes for the future - I merged this to dev so that Mike, Wendy, or others can play with it. There are a few other things i have in mind - tweaking styles on the bullets and fiddling with dimensions so that it all fits on the screen in a handy way - little things like that. Plus, as work continues on feature-data-vis-module, we'll update the subtopic links go to to `/data-explorer/subtopic#indicator` or something like that. Let's keep this branch around for ongoing work.

**Comment by mmontesanonyc** [comment]
Just committed some `no-bullets` styles for the uls so that we fix the table alignment. A few low priority things to get to at some point (perhaps once we resume focus on this once we have data-vis-module progress?

- [ ] small issue with the DataTable responsiveness that we should look into - the header and body don't really resize to match each other, though they'll load/re-load properly.
- [ ] Language - we're using our legacy language of "indicators" and "subtopics." I think this will likely change before we launch. Maybe "datasets" and "topics"? (But this conflicts with how we refer to things on key topic pages - where we refer to subtopics as "datasets.") Worth noting that our language is still up in the air, and we'll want to move toward consistency across different areas.

**Comment by mmontesanonyc** [comment]
(Made a couple of improvements to responsiveness and header-alignment issues on the DataTables, so am merging those commits into dev and re-building there. Assuming more work will happen on this branch, not merging these to main just yet)

**Comment by cgettings** [comment]
Agree. Let's close.
