### ISSUE TITLE
Consider EHS section

### ISSUE THREAD

**Issue by mmontesanonyc** [nycehs/ehs-data-portal-frontend-temp#164]
In chatting with Mike we kicked around the idea of an EHS section that's a little bit different from the rest of the content organization. Maybe it could be a top-level section, but doesn't appear in the nav structure (possibly expanding on the About Us page?). 

Among other things, it could host Reports. We currently have this content type (nyccas report, heat mortality report) sort of filed at the same level as 'data features' but maybe this doesn't work. Data features (air quality explorer, interactive HVI, syndromic, realtime, etc) could just be re-built as data stories (just more interaction, less narrative than other data stories), and the reports could be moved into this EHS/reports content type. 

This gives us room to expand other EHS-specific content and consider using the portal as an umbrella for more services. And, it lets us get rid of a potentially confusing distinction on the key topics page of 'data features' and 'data stories.'

**Comment by cgettings** [comment]
I like the "data stories with less narrative" thing better than this idea, but: maybe data stories could be a _type_ of data feature?

**Comment by mmontesanonyc** [comment]
Interesting. Yeah. 

One thing that would let us do is tidy up the layout of the Key Topics page, which I haven't been too happy with. Instead of what we have there, we could just have three columns below the main text: Data sets, Neighborhood Reports, and Data Features. Data Features (or whatever we title it) could have different icons - one icon for data stories and another for interactives. 

I'm not sure if "Data features" is the right title for this, but either way I think I like the idea of grouping the current data features with data stories. The current data features are built as subpages to the key topics, so they (might?) need to be moved into the data stories section. Or, we leave them where they are, but just re-organize the front-end. 

![image](https://user-images.githubusercontent.com/55593359/158812941-72111f1f-9d8c-4266-8b43-3495ce525c41.png)

**Comment by mmontesanonyc** [comment]
An EHS section can live in `/about` and stay out of the Data Portal info architecture, but still provide the org-level description and content, like reports.
