### ISSUE TITLE
Update .URL references so site is compatible with future Hugo versions

### ISSUE THREAD

**Issue by mmontesanonyc** [nycehs/ehs-data-portal-frontend-temp#165]
Current version of Hugo throws errors when building. Site can be built with 0.8.x versions. 

Error is this:

`ERROR 2022/03/11 15:18:19 Page.URL is deprecated and will be removed in Hugo 0.93.0. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url`

So, go through and change Page.URL references to .Permalink or .RelPermalink as suggested by the error.

**Comment by cgettings** [comment]
The change in [themes/dohmh/layouts/partials/header.html](https://github.com/nycehs/ehs-data-portal-frontend-temp/commit/112ae2b002f6383a3039063396b52a0b16061807#diff-614ba7c3688a1b8fc1a892edb7ef5d3b5f602e1d502121ddee3ce86b9db3d23c) might be a good place to start to clarify what this issue is, and what the .Permalink thing is doing and why.

**Comment by mmontesanonyc** [comment]
Hey, thanks for digging in to this!

Yeah, I'm seeing the issue. In layouts/_default/baseof.html, there's that code to use the simplified header (header-ds) with the data stories, instead of the full header. But with this change from .URL to .Permalink, that if code is capturing the data stories landing page, too. 

I think the part that's not working is line 15, ...`( eq .Permalink "/data-stories/")`. Hugo isn't interpreting the Data Stories landing page as having `.Permalink = /data-stories/`

One way we can test Hugo variables is to print them to a page location (the way you'd use console.log in js). I'll commit that so we can test to see what that page's Permalink value is, so we can use it there and get that if/than working.
