### ISSUE TITLE
Add content translations

### ISSUE THREAD

**Issue by cgettings** [nycehs/ehs-data-portal-frontend-temp#183]
Follow steps in https://www.regisphilibert.com/blog/2018/08/hugo-multilingual-part-1-managing-content-translation/

**Comment by mmontesanonyc** [comment]
OK, I re-read that, and I _think_ the way to go is:
- use "managing translations by Filename" and create `/content/data-stories/povasthma/index.es.md` for example
- update config.yaml
- from povasthma, we can link to the Spanish and Chinese versions by referencing `{{ .Translations }}` or `{{ .AllTranslations }}`  - Regis Philibert includes this handy bit:

```
{{ if .IsTranslated }}
	{{ range .Translations }}
	<link rel="alternate" hreflang="{{ .Language.Lang }}" href="{{ .Permalink }}" title="{{ .Language.LanguageName }}">
	{{ end }}
{{ end }}
```

I'm not entirely clear about the scope of some of the things that Philibert describes, so we'll have to test, but I think for our use case - managing a handful of stuff for which we have manually translated content (as opposed to any site-wide, dynamic translation?) - this is the path. What do you think?

**Comment by cgettings** [comment]
Looks right to me, but I'll work through it to check.

**Comment by mmontesanonyc** [comment]
I was about to say "let's talk this afternoon about divvying up tasks" but I don't know if I'll get to adding content today/tomorrow, and then I'm out all next week.

**Comment by cgettings** [comment]
How do users get to the translations? Do we put a language nav link at the top of the page, like he does; or do we rely on the language links at the bottom of the city template; or some other way?

**Comment by cgettings** [comment]
One problem: we have translations for the datawrapper titles and descriptions, but the text that displays comes from the chart spec on datawrapper. I'm not sure how we'd deal with this. Maybe datawrapper has written something about this?

**Comment by mmontesanonyc** [comment]
There are a couple things we can do. We can either create fully-translated parallel versions of each DW chart, or we can hide the title and description from the chart and build those on page instead.

**Comment by mmontesanonyc** [comment]
> How do users get to the translations? Do we put a language nav link at the top of the page, like he does; or do we rely on the language links at the bottom of the city template; or some other way?

I've been chewing this over and I think it's something like a partial on the page (recall - a partial is a templated component) that gets added if the page has other translations. And the partial can say (in those languages) "Read this in Spanish" / "Read this in Chinese." Maybe that goes on the bottom of the page (above the footer), or in the sidebar? Or even at the top of the content?

**Comment by cgettings** [comment]
This is what it looks like in my recent commit:

![Screenshot (371)](https://user-images.githubusercontent.com/12686912/162984143-cab793c5-9825-4d37-b482-91ab252f08db.png)

which I did by putting this above `{{.Content}}` in all the data story templates:

```
{{ if .IsTranslated }}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            {{ range .Translations }}
            <li><a href="{{ .Permalink }}">{{ .Language.LanguageName }}</a>&nbsp;|&nbsp;</li>  
            {{ end }}
        </ul>
    </div>
</nav>
{{ end }}
```

Pretty basic, but it works. Maybe we can talk about the partial solution on Thursday.

**Comment by mmontesanonyc** [comment]
Nice - I think that's the perfect place to start.

**Comment by cgettings** [comment]
- [ ] Create translated Datawrapper charts

**Comment by mmontesanonyc** [comment]
- [ ] covidair
- [ ] Geographies
- [ ] Povasthma
- [ ] housing
- [ ] violence
- [ ] redlining

**Comment by mmontesanonyc** [comment]
[Datawrapper charts are translated](https://github.com/nycehs/ehs-data-portal-frontend-temp/issues/183), and I'll handle violence-es and violence-cn early next. Nice to have progress on these. 

Next step will be bouncing them over to Eriksen for review - I flagged a few things that still need to be translated.

**Comment by mmontesanonyc** [comment]
- [ ] Merged to dev
- [ ] Merged to main

**Comment by mmontesanonyc** [comment]
Noticing on that on [violence-es](https://nycehs.github.io/ehs-data-portal-frontend-temp/es/data-stories/violence/), a few charts are 404ing out. I think I would have noticed that earlier so I'm wondering if something borked. 

Did a quick scan of other data stories in spanish, as well as violence-cn, with no other issues so it's probably just something I overlooked. Will fix.

**Comment by mmontesanonyc** [comment]
Look at english and spanish maps for consistency.

**Comment by mmontesanonyc** [comment]
Oh! This is done.
