### ISSUE TITLE
Consider citation component

### ISSUE THREAD

**Issue by mmontesanonyc** [nycehs/ehs-data-portal-frontend-temp#188]
Thinking about a function on the vis page that automatically generates a citation that people can copy. We'd have to choose style, but can grab the source, year, and feed it into a citation with "Access at: " and other necessary info.

**Comment by cgettings** [comment]
How detailed? Like, if it’s ACS data, do we mention table, variable, link to their data explorer page with that data in view?

I guess my real question is, who’s the audience and what’s the purpose?

**Comment by mmontesanonyc** [comment]
Hmmmmmmmmmmmmmmm.

One thing I'd like to do with this and similar things is, like, create more usable information with the information we already have. So I think I'd like to stick with information readily available on the page or via indicators.json. So a citation format that's something like, NYC Department of Health, `TOPIC` Data.` SOURCE` (`YEAR`), Accessed at `URL`, `DATE`. 

I think that gives a fairly general citation that's suits what I would expect to be most use cases where a citation is necessary. The problem might be whether using a topic name is sufficient to refer to an indicator. I _think_ it will be but we'll see.

One way I'm imagining implementing this is, just building it in javascript as a variable, with a "copy citation" button below the data - something like that. "Copied!"

**Comment by mmontesanonyc** [comment]
[Moved to EH-dataportal](https://github.com/nychealth/EH-dataportal/issues/5).
