### ISSUE TITLE
Create translated Datawrapper charts

### ISSUE THREAD

**Issue by cgettings** [nycehs/ehs-data-portal-frontend-temp#194]
Re: #183

**Comment by mmontesanonyc** [comment]
- [ ] Reorganize Datawrapper charts by data story title
- [ ] Tidy drafts
- [ ] Create translated versions

**Comment by mmontesanonyc** [comment]
- [ ] Housing-es
- [ ] Housing-cn
- [ ] Violence-es
- [ ] Violence-cn
- [ ] Redlining-es
- [ ] Redlining-cn
