### ISSUE TITLE
Investigate conditional modal

### ISSUE THREAD

**Issue by mmontesanonyc** [nycehs/ehs-data-portal-frontend-temp#227]
Modal that says that this is a prototype site should build on dev only - wrap modal in environment test?

Additionally, investigate ability to build this so that it appears on any page, but on user's entrance to the site only. How to do this?

**Comment by cgettings** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

**Comment by cgettings** [comment]
Set a session storage value with the current date and time, and some key:

`if (sessionStorage) {
			sessionStorage.setItem(SESSION_KEY, Date.now()); `

Only show the modal if it’s been more than 24 hours since the session started:

`if (sessionStorage) {
		var session = sessionStorage.getItem(SESSION_KEY);
		// open the dialog only every 24 hours
		if (session && Date.now() - session < ONE_DAY_MILLI_SEC) {
			return; // stops eval
		}
	}
`

**Comment by cgettings** [comment]
So we just wrap the modal code in a function like [here](https://leafletjs.com/dialog/dialog.js), then call it on every page, and we should be set.

**Comment by mmontesanonyc** [comment]
[Moving to EH-dataportal](https://github.com/nychealth/EH-dataportal/issues/6).
