### ISSUE TITLE
Layout tweaks to data-explorer template page (vis module)

### ISSUE THREAD

**Issue by mmontesanonyc** [nycehs/ehs-data-portal-frontend-temp#239]
Some other items to address with the Data Explorer - mostly small layout things:

- Fix, improve, or remove the "show more"/"show less" button for topic content
- Change styling for topic content - see the class "subtopiccontainer" for inspiration, making H2 and H3 smaller and subtler. 
- Consider having the "change indicator" button be full-width and show the title of the indicator
- Remove "indicator description" prompt (but keep the description content)
- Dump How Calculated and Notes/Sources into accordions.
- Remove outline on Vega-Lite specs

**Comment by cgettings** [comment]
Not sure if this counts as “layout”, but I’d like to format large numbers with commas

**Comment by mmontesanonyc** [comment]
Good catch. 
We could turn off the legend, or might be able to situate it above or below - just via the spec, so should be easy for us.

**Comment by mmontesanonyc** [comment]
Agreed. Should just be small tweaks to the bootstrap classes.

**Comment by cgettings** [comment]
It looks like the Notes field hasn't been added to the viz mod page yet.

Compare *Asthma Emergency Department Visits (Adults)* on [nowportal](https://a816-dohbesp.nyc.gov/IndicatorPublic/VisualizationData.aspx?id=2380,4466a0,11,Summarize) vs. [futureportal](https://nycehs.github.io/ehs-data-portal-frontend-temp/data-explorer/asthma/)

**Comment by mmontesanonyc** [comment]
Tweaking mobile display - we can change a class from device-sm to device-xs to get that proper breakpoint for horizontal icon display for those tabs.

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/55593359/175945402-48d333db-0f60-4bbd-82e3-f7233dbbc658.png">

**Comment by cgettings** [comment]
very nice

**Comment by cgettings** [comment]
I agree. Nice easy on-ramp to the work week, too.
