### ISSUE TITLE
Revise datawrapper shortcode

### ISSUE THREAD

**Issue by mmontesanonyc** [nycehs/ehs-data-portal-frontend-temp#63]
The datawrapper shortcode is written so that you pass 3 arguments in, sequentially:
```{{< datawrapper "Title" "chartID/version/" "Height" >}}```

However, it's a little more natural to do this the way we've done it with the vega shortcode, where we make it more clear what the arguments are. 
```{{< vega id="uniqueDivID" spec="../../visualizations/spec/bartest.vl.json" >}}```

So, at some point, re-build the datawrapper shortcode (and any uses of it!) so that its format roughly matches that of the vega shortcode. 

datawrapper.html:
```
</div>
<div class="wide my-4">
<iframe title="{{ index .Params 0}}" aria-label="Interactive chart" id="datawrapper-chart-O0SUA" src="//datawrapper.dwcdn.net/{{ index  .Params 1}}" scrolling="no" frameborder="0"
style="width: 0; min-width: 100% !important; border: none;" height="{{  index .Params 2}}"></iframe> <script type="text/javascript">!function () { "use strict"; window.addEventListener("message", function (a) { if (void 0 !== a.data["datawrapper-height"]) for (var e in a.data["datawrapper-height"]) { var t = document.getElementById("datawrapper-chart-" + e) || document.querySelector("iframe[src*='" + e + "']"); t && (t.style.height = a.data["datawrapper-height"][e] + "px") } }) }();
</script>
</div>
<div class="narrow">
```

vega.html:
```
<div id='{{ .Get "id" }}' style="width:100%; height: {{ .Get `height` }}"></div>
<script type="text/javascript">
  var spec = '{{ .Get "spec" }}';
  vegaEmbed('#{{ .Get "id" }}', spec).then(function(result) {
    // TOOD: do something?
  }).catch(console.error);
</script>
```

**Comment by cgettings** [comment]
I used find and replace with a regex pattern:

Pattern: `^(\{\{<\s*datawrapper\s*)(".+")\s*(".+")\s*(".+")(\s*>\}\})`
Replacement: `$1 title=$2 src=$3 height=$4 $5`

It was pretty easy, actually.
There's documentation [here](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_search-and-modify).
