### ISSUE TITLE
Problem: only Active Design visualizations render

### ISSUE THREAD

**Issue by mmontesanonyc** [nycehs/ehs-data-portal-frontend-temp#7]
Fixing path issues fixed Active Design report data, but other reports don't find data. It might just be a filename issue. Asthma is looking for something called

`http://localhost:1313/ehs-data-portal-frontend-temp/visualizations/csv/Asth1196.csv
`
![image](https://user-images.githubusercontent.com/55593359/130067657-4882f269-7a66-4d76-9da9-2c1778588ce6.png)

But, we don't have a corresponding file by that name. The first step is probably to identify that URL in the code and change it to the existing filename. 

![image](https://user-images.githubusercontent.com/55593359/130067810-e9bd4722-4f70-4181-b2b4-8a70da1ffcab.png)

**Comment by grantpezeshki** [comment]
I think somehow the data csvs were not included in this version of the repo; I'm going to re-run the python scripts to rebuild the data and verify that they are all in there. The data file you've highlighted is an earlier iteration of the visualization design; instead now the csvs are one per measure. Will expand on this as I get back into the data; thanks for creating this issue.

**Comment by mmontesanonyc** [comment]
The situation is that in the Neighborhood Reports, there are 5 report types: Active Design, Asthma, Climate, Housing, and Outdoor Air. The visualizations for the Active Design reports render - but for other reports, if you click an indicator, no viz. That's because the page is looking for data files that don't exist. They need to be in this folder: https://github.com/nycehs/ehs-data-portal-frontend-temp/tree/main/static/visualizations/csv

The data are there, in those files with names that correspond to the reports - Asthma and the Environment_data.csv, Climate and Health_data.csv, etc etc. 

So the job is to take those big files and break them out into indicator-specific files, the way that Grant has done for the Active Design report - see, for example, bikeEDAA.csv and bikeEDAA_trend.csv. 
The non-trend files just have geo_join_id, Neighborhood, Value, and Message columns 
The trend files have Start Date, Time, geo join ID, Neighborhood, Value, and Message.
And, the new files will need names that the system is looking for. You can find these names in the report spec JSON, which are here (there is one file for each neighborhood/report combination, but you'll only need to look up each of the 5 report types: active design, asthma, climate, housing, outdoor air). Each json file references the indicators, and there's a field called indicator_data_name that corresponds to the name of the file that the system will look for. So, that's where you'll find the filenames that the indicator-specific files will need.

**Comment by mmontesanonyc** [comment]
@cgettings, when you run these files, you can add them to [this branch](https://github.com/nycehs/ehs-data-portal-frontend-temp/tree/hotfix-NR-data-update) locally, and serve (``hugo serve --environment local --disableFastRender``) to test, and then commit.

**Comment by cgettings** [comment]
We never found the scripts for this, right? So I’m starting from scratch?

**Comment by mmontesanonyc** [comment]
There are scripts that export the full-report CSV files, but, there are no scripts to break down the full-report csvs into indicator-specific csvs. So yes.

Worth noting that there are a few enhancements we can make down the line - refactoring the front-end code to use the full-report CSVs (filter by indicator, etc); and, a little further down (after we launch the data explorer vis module), we can refactor the NRs to use the indicator data used by the Data Explorer.

**Comment by cgettings** [comment]
Which page are you referring to when you say “the page is looking for data files that don't exist”?

**Comment by mmontesanonyc** [comment]
Any of the [report output pages](https://nycehs.github.io/ehs-data-portal-frontend-temp/neighborhood_reports/east_flatbush_flatbush/asthma_and_the_environment/), once you click on an indicator to bring up the modal.

![image](https://user-images.githubusercontent.com/55593359/146553383-c814c219-491a-4541-bb0e-22e52e4634c7.png)

![image](https://user-images.githubusercontent.com/55593359/146553450-ec68674d-721f-4d24-a1e8-131325072617.png)

**Comment by mmontesanonyc** [comment]
hey so! the data update has solved this, so we can close the issue. haven't yet merged the changes from NR-data-update into development yet - I'm making a few more tweaks that I'd love to talk through next week. But i think it's safe to close this issue. thanks again for running this data update - I think the NRs are like 98% of the way done.
